// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _201_samples.Migrations
{
    [DbContext(typeof(FoodModel))]
    [Migration("20221004153031__02_SecondMealAdd")]
    partial class _02_SecondMealAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("MealVerF", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MealId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("NHFoodVerF", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodSteps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodViews")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MealVerFMealId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodId");

                    b.HasIndex("MealVerFMealId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("NHFoodVerF", b =>
                {
                    b.HasOne("MealVerF", null)
                        .WithMany("foods")
                        .HasForeignKey("MealVerFMealId");
                });

            modelBuilder.Entity("MealVerF", b =>
                {
                    b.Navigation("foods");
                });
#pragma warning restore 612, 618
        }
    }
}
